// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rpmcypajakgqkzqvsjwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwbWN5cGFqYWtncWt6cXZzandkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MzgwNzQsImV4cCI6MjA3NTExNDA3NH0.43-w0Eh9jEQSa0tDD1teKPmz_rwIuDjpPsuG7RPcQCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);